using CastLibrary.Repository;
using CastLibrary.Repository.Mappers;
using CastLibrary.Repository.Repositories;
using CastLibrary.Repository.Repositories.Delete;
using CastLibrary.Repository.Repositories.Insert;
using CastLibrary.Repository.Repositories.Read;
using CastLibrary.Repository.Repositories.Update;
using CastLibrary.Repository.Services;

namespace CastLibrary.WebHost.IoC
{
    public static class IOCRepository
    {
        public static IServiceCollection AddRepository(this IServiceCollection services)
        {
            AddMappers(services);
            services.AddScoped<ISqlConnectionFactory, SqlConnectionFactory>();
            services.AddScoped<IKeywordExtractionService, KeywordExtractionService>();
            services.AddScoped<IUserReadRepository, UserReadRepository>();
            services.AddScoped<IUserInsertRepository, UserInsertRepository>();
            services.AddScoped<IUserUpdateRepository, UserUpdateRepository>();
            services.AddScoped<IUserDeleteRepository, UserDeleteRepository>();
            services.AddScoped<IUserWriteRepository, UserWriteRepository>();
            services.AddScoped<ICastReadRepository, CastReadRepository>();
            services.AddScoped<ICastInsertRepository, CastInsertRepository>();
            services.AddScoped<ICastUpdateRepository, CastUpdateRepository>();
            services.AddScoped<ICastDeleteRepository, CastDeleteRepository>();
            services.AddScoped<ILocationReadRepository, LocationReadRepository>();
            services.AddScoped<ILocationInsertRepository, LocationInsertRepository>();
            services.AddScoped<ILocationUpdateRepository, LocationUpdateRepository>();
            services.AddScoped<ILocationDeleteRepository, LocationDeleteRepository>();
            services.AddScoped<ISublocationReadRepository, SublocationReadRepository>();
            services.AddScoped<ISublocationInsertRepository, SublocationInsertRepository>();
            services.AddScoped<ISublocationUpdateRepository, SublocationUpdateRepository>();
            services.AddScoped<ISublocationDeleteRepository, SublocationDeleteRepository>();
            services.AddScoped<ICampaignReadRepository, CampaignReadRepository>();
            services.AddScoped<ICampaignInsertRepository, CampaignInsertRepository>();
            services.AddScoped<ICampaignUpdateRepository, CampaignUpdateRepository>();
            services.AddScoped<ICampaignDeleteRepository, CampaignDeleteRepository>();
            services.AddScoped<ISecretReadRepository, SecretReadRepository>();
            services.AddScoped<ISecretInsertRepository, SecretInsertRepository>();
            services.AddScoped<ISecretUpdateRepository, SecretUpdateRepository>();
            services.AddScoped<ISecretDeleteRepository, SecretDeleteRepository>();
            services.AddScoped<IUserInsertRepository, UserInsertRepository>();
            services.AddScoped<IUserUpdateRepository, UserUpdateRepository>();
            services.AddScoped<IPasswordResetTokenReadRepository, PasswordResetTokenReadRepository>();
            services.AddScoped<IPasswordResetTokenInsertRepository, PasswordResetTokenInsertRepository>();
            services.AddScoped<IPasswordResetTokenUpdateRepository, PasswordResetTokenUpdateRepository>();
            services.AddScoped<ICampaignCastRelationshipReadRepository, CampaignCastRelationshipReadRepository>();
            services.AddScoped<ICampaignCastRelationshipDeleteRepository, CampaignCastRelationshipDeleteRepository>();
            services.AddScoped<ICampaignCastRelationshipInsertRepository, CampaignCastRelationshipInsertRepository>();
            services.AddScoped<ICampaignCastRelationshipUpdateRepository, CampaignCastRelationshipUpdateRepository>();
            services.AddScoped<ICampaignInviteCodeReadRepository, CampaignInviteCodeReadRepository>();
            services.AddScoped<ICampaignInviteCodeUpdateRepository, CampaignInviteCodeUpdateRepository>();
            services.AddScoped<ICampaignInviteCodeDeleteRepository, CampaignInviteCodeDeleteRepository>();
            services.AddScoped<ICampaignPlayerReadRepository, CampaignPlayerReadRepository>();
            services.AddScoped<ICampaignPlayerInsertRepository, CampaignPlayerInsertRepository>();
            services.AddScoped<ICampaignPlayerDeleteRepository, CampaignPlayerDeleteRepository>();
            services.AddScoped<ICastPlayerNotesReadRepository, CastPlayerNotesReadRepository>();
            services.AddScoped<ICastPlayerNotesUpdateRepository, CastPlayerNotesUpdateRepository>();
            services.AddScoped<ILocationPlayerNotesReadRepository, LocationPlayerNotesReadRepository>();
            services.AddScoped<ILocationPlayerNotesUpdateRepository, LocationPlayerNotesUpdateRepository>();
            services.AddScoped<IAdminInviteCodeReadRepository, AdminInviteCodeReadRepository>();
            services.AddScoped<IAdminInviteCodeUpdateRepository, AdminInviteCodeUpdateRepository>();
            services.AddScoped<IAdminInviteCodeDeleteRepository, AdminInviteCodeDeleteRepository>();
            services.AddScoped<ITimeOfDayReadRepository, TimeOfDayReadRepository>();
            services.AddScoped<ITimeOfDayWriteRepository, TimeOfDayWriteRepository>();
            services.AddScoped<IPlayerCardReadRepository, PlayerCardReadRepository>();
            services.AddScoped<IPlayerCardInsertRepository, PlayerCardInsertRepository>();
            services.AddScoped<IPlayerCardUpdateRepository, PlayerCardUpdateRepository>();
            services.AddScoped<IPlayerCardDeleteRepository, PlayerCardDeleteRepository>();
            services.AddScoped<IPlayerCardConditionReadRepository, PlayerCardConditionReadRepository>();
            services.AddScoped<IPlayerCardConditionInsertRepository, PlayerCardConditionInsertRepository>();
            services.AddScoped<IPlayerCardConditionDeleteRepository, PlayerCardConditionDeleteRepository>();
            services.AddScoped<IPlayerCardMemoryReadRepository, PlayerCardMemoryReadRepository>();
            services.AddScoped<IPlayerCardMemoryInsertRepository, PlayerCardMemoryInsertRepository>();
            services.AddScoped<IPlayerCardMemoryDeleteRepository, PlayerCardMemoryDeleteRepository>();
            services.AddScoped<IPlayerCardTraitReadRepository, PlayerCardTraitReadRepository>();
            services.AddScoped<IPlayerCardTraitInsertRepository, PlayerCardTraitInsertRepository>();
            services.AddScoped<IPlayerCardTraitUpdateRepository, PlayerCardTraitUpdateRepository>();
            services.AddScoped<IPlayerCardTraitDeleteRepository, PlayerCardTraitDeleteRepository>();
            services.AddScoped<IPlayerCardSecretReadRepository, PlayerCardSecretReadRepository>();
            services.AddScoped<IPlayerCardSecretInsertRepository, PlayerCardSecretInsertRepository>();
            services.AddScoped<IPlayerCardSecretUpdateRepository, PlayerCardSecretUpdateRepository>();
            services.AddScoped<IPlayerCardSecretDeleteRepository, PlayerCardSecretDeleteRepository>();
            services.AddScoped<IPlayerCastPerceptionReadRepository, PlayerCastPerceptionReadRepository>();
            services.AddScoped<IPlayerCastPerceptionInsertRepository, PlayerCastPerceptionInsertRepository>();
            services.AddScoped<IPlayerCastPerceptionUpdateRepository, PlayerCastPerceptionUpdateRepository>();
            services.AddScoped<IGoldTransactionInsertRepository, GoldTransactionInsertRepository>();
            services.AddScoped<ICurrencyBalanceReadRepository, CurrencyBalanceReadRepository>();
            services.AddScoped<ICurrencyTransactionUpdateRepository, CurrencyTransactionUpdateRepository>();
            services.AddScoped<IBugReportInsertRepository, BugReportInsertRepository>();
            services.AddScoped<IBugReportReadRepository, BugReportReadRepository>();
            services.AddScoped<IBugReportUpdateRepository, BugReportUpdateRepository>();
            services.AddScoped<IBugReportDeleteRepository, BugReportDeleteRepository>();
            services.AddScoped<IFactionReadRepository, FactionReadRepository>();
            services.AddScoped<IFactionInsertRepository, FactionInsertRepository>();
            services.AddScoped<IFactionUpdateRepository, FactionUpdateRepository>();
            services.AddScoped<IFactionDeleteRepository, FactionDeleteRepository>();
            services.AddScoped<IFactionPlayerNotesReadRepository, FactionPlayerNotesReadRepository>();
            services.AddScoped<IFactionPlayerNotesUpdateRepository, FactionPlayerNotesUpdateRepository>();
            services.AddScoped<ISublocationPlayerNotesReadRepository, SublocationPlayerNotesReadRepository>();
            services.AddScoped<ISublocationPlayerNotesUpdateRepository, SublocationPlayerNotesUpdateRepository>();
            services.AddScoped<ICampaignPlayerNotesReadRepository, CampaignPlayerNotesReadRepository>();
            services.AddScoped<ICampaignPlayerNotesUpdateRepository, CampaignPlayerNotesUpdateRepository>();
            services.AddScoped<ICampaignEventInsertRepository, StorylineInsertRepository>();
            services.AddScoped<IStorylineReadRepository, StorylineReadRepository>();
            services.AddScoped<IStorylineUpdateRepository, StorylineUpdateRepository>();
            services.AddScoped<ICampaignEventDeleteRepository, StorylineDeleteRepository>();
            services.AddScoped<ICampaignSessionChroniclesReadRepository, CampaignSessionChroniclesReadRepository>();
            services.AddScoped<ICampaignSessionChroniclesInsertRepository, CampaignSessionChroniclesInsertRepository>();
            services.AddScoped<ISessionReadRepository, SessionReadRepository>();
            services.AddScoped<ISessionInsertRepository, SessionInsertRepository>();
            services.AddScoped<ISessionUpdateRepository, SessionUpdateRepository>();
            services.AddScoped<ICampaignSessionArchivedInsertRepository, CampaignSessionArchivedInsertRepository>();
            services.AddScoped<ICampaignChroniclesReadRepository, CampaignChroniclesReadRepository>();
            services.AddScoped<ICampaignChroniclesUpdateRepository, CampaignChroniclesUpdateRepository>();
            services.AddScoped<ISessionDeleteRepository, CampaignSessionArchivedDeleteRepository>();
            services.AddHealthChecks()
              .AddCheck<DatabaseHealthCheck>("postgres");

            return services;
        }

        private static void AddMappers(IServiceCollection services)
        {
            services.AddScoped<ICampaignInviteCodeEntityMapper, CampaignInviteCodeEntityMapper>();
            services.AddScoped<ICampaignEntityMapper, CampaignEntityMapper>();
            services.AddScoped<ICastEntityMapper, CastEntityMapper>();
            services.AddScoped<ILocationEntityMapper, LocationEntityMapper>();
            services.AddScoped<IPasswordResetTokenEntityMapper, PasswordResetTokenEntityMapper>();
            services.AddScoped<IUserEntityMapper, UserEntityMapper>();
            services.AddScoped<ICampaignCastRelationshipEntityMapper, CampaignCastRelationshipEntityMapper>();
            services.AddScoped<ICampaignCastPlayerNotesEntityMapper, CampaignCastPlayerNotesEntityMapper>();
            services.AddScoped<ICampaignLocationPlayerNotesEntityMapper, CampaignLocationPlayerNotesEntityMapper>();
            services.AddScoped<ICampaignSecretEntityMapper, CampaignSecretEntityMapper>();
            services.AddScoped<ICampaignPlayerEntityMapper, CampaignPlayerEntityMapper>();
            services.AddScoped<IAdminInviteCodeEntityMapper, AdminInviteCodeEntityMapper>();
            services.AddScoped<IPlayerCardEntityMapper, PlayerCardEntityMapper>();
            services.AddScoped<IPlayerCardConditionEntityMapper, PlayerCardConditionEntityMapper>();
            services.AddScoped<IPlayerCardMemoryEntityMapper, PlayerCardMemoryEntityMapper>();
            services.AddScoped<IPlayerCardTraitEntityMapper, PlayerCardTraitEntityMapper>();
            services.AddScoped<IPlayerCardSecretEntityMapper, PlayerCardSecretEntityMapper>();
            services.AddScoped<IPlayerCastPerceptionEntityMapper, PlayerCastPerceptionEntityMapper>();
            services.AddScoped<IBugReportEntityMapper, BugReportEntityMapper>();
            services.AddScoped<IFactionEntityMapper, FactionEntityMapper>();
            services.AddScoped<ICampaignFactionInstanceEntityMapper, CampaignFactionInstanceEntityMapper>();
            services.AddScoped<ICampaignFactionPlayerNotesEntityMapper, CampaignFactionPlayerNotesEntityMapper>();
            services.AddScoped<ICampaignSublocationPlayerNotesEntityMapper, CampaignSublocationPlayerNotesEntityMapper>();
            services.AddScoped<ICampaignPlayerNotesEntityMapper, CampaignPlayerNotesEntityMapper>();
            services.AddScoped<ICampaignSessionChroniclesEntityMapper, CampaignSessionChroniclesEntityMapper>();
            services.AddScoped<IPlayerQuicknoteQueueEntityMapper, PlayerQuicknoteQueueEntityMapper>();
            services.AddScoped<ICampaignEventEntityMapper, CampaignEventEntityMapper>();
            services.AddScoped<ISubscriptionEntityMapper, SubscriptionEntityMapper>();
            services.AddScoped<IPricingModelEntityMapper, PricingModelEntityMapper>();
            services.AddScoped<IQuicknoteQueueReadRepository, QuicknoteQueueReadRepository>();
            services.AddScoped<IQuicknoteQueueInsertRepository, QuicknoteQueueInsertRepository>();
            services.AddScoped<IQuicknoteQueueUpdateRepository, QuicknoteQueueUpdateRepository>();
            services.AddScoped<IQuicknoteQueueDeleteRepository, QuicknoteQueueDeleteRepository>();
            services.AddScoped<ICastcardsConfigurationReadRepository, CastcardsConfigurationReadRepository>();
            services.AddScoped<ICastcardsConfigurationInsertRepository, CastcardsConfigurationInsertRepository>();
            services.AddScoped<ICastcardsConfigurationUpdateRepository, CastcardsConfigurationUpdateRepository>();
            services.AddScoped<ICampaignLocationInstanceReadRepository, CampaignLocationInstanceReadRepository>();
            services.AddScoped<ICampaignSublocationInstanceReadRepository, CampaignSublocationInstanceReadRepository>();
            services.AddScoped<ICampaignCastInstanceReadRepository, CampaignCastInstanceReadRepository>();
            services.AddScoped<ICampaignFactionInstanceReadRepository, CampaignFactionInstanceReadRepository>();
            services.AddScoped<ISubscriptionReadRepository, SubscriptionReadRepository>();
            services.AddScoped<ISubscriptionWriteRepository, SubscriptionWriteRepository>();
            services.AddScoped<ISubscriptionUpdateRepository, SubscriptionUpdateRepository>();
            services.AddScoped<IPricingModelReadRepository, PricingModelReadRepository>();
            services.AddScoped<IPricingModelUpdateRepository, PricingModelUpdateRepository>();
            services.AddScoped<IAuditReadRepository, AuditReadRepository>();
        }
    }
}
